### ISSUE TITLE
Can't open any pages (tag 3.10.0 and 3.11.0)

### ISSUE THREAD

**Issue by Amy0511** [boomerang-io/flow.client.web#169]
**Describe the bug**
Can't open flow pages after deployed flow front end app with tag 3.10.0 and 3.11.0.

**To Reproduce**
Deploy flow front end app with tag 3.10.0 and 3.11.0.

- Commands to run
- Interactions to cause issue to happen

**Expected behavior**
Pages should be opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/87841473/190542156-0e215082-bf90-46ae-bc83-bdd82818edc6.png)

**Environment (please complete the following information):**

- OS: [e.g. MacOS]
- Browser [chrome]
- Version [3.10.0 and 3.11.0 have problems, 3.9.12 works fine]

**Additional context**

**Comment by Amy0511** [comment]
From the server logs, there is no `build/index.html`.  I have no access to the CICD pipeline and can't check the build logs to see if there is a step of npm build like "`pnpm run build`" or "`npm run build`". So open a defect for it.
@gchickma @timrbula

**Comment by tlawrie** [comment]
Hi @Amy0511 can I confirm that you are using the right tag.

The release is [3.11.0](https://github.com/boomerang-io/roadmap/releases/tag/3.11.0) but the web client tag is `3.9.12`

**Comment by tlawrie** [comment]
Or are you using the latest tags that haven't been a part of a published release?

If so, can you see the GitHub Actions for the CICD logs? https://github.com/boomerang-io/flow.client.web/actions

**Comment by Amy0511** [comment]
@tlawrie I am not sure what release I used. I just know I use the image with tag 3.11.0 `boomerangio/flow-client-web:3.11.0`. I just delivered a fix for the issue "can't open task yaml after created a task by importing yaml" and the fix is in 3.11.0

**Comment by tlawrie** [comment]
Ok. That will have to be a @timrbula or @BenjaminRuby question

**Comment by Amy0511** [comment]
From the package.json Line10, there is a script  `"postbuild": "ncp build server/build"` to copy the build folder to server. But didn't find the script run in the CICD logs. https://github.com/boomerang-io/flow.client.web/actions

**Comment by timrbula** [comment]
@Amy0511 thanks for finding this. Looks like it came from the migration to `pnpm` which doesn't run the `pre` and `post` scripts by convention. In this case, it was not running the `postbuild` step to move the build assets over to the server directory.

I've pushed up the changes

**Comment by timrbula** [comment]
I've fixed the version for the 3.11 release (tag 3.10.1 now) and the current release 3.12 on main (tag 3.11.1).
