### ISSUE TITLE
Python based worker task

### ISSUE THREAD

**Issue by morarucostel** [boomerang-io/flow.client.web#39]
Currently the flow task that is in the `worker.flow` component is based on alpine image and is using the PythonShell library to send python instructions to the underlying python layer. 
It supports basic required libraries imports through a specific field and by running `pip3 install -r requirements.txt` .

However if more advanced requirements are needed like pandas or others that require a c compilation or dev suite, the task is not able to install them via the pip3 because the base image doesn't have the python dev environment. 

The task is to create a python based Flow specific image that will allow the extensibility of more advanced imports needed for the python script. 
In addition it should support the lifecycle mechanism of the workflow.

**Comment by tlawrie** [comment]
Hi @morarucostel should this be raised under roadmap or the flow web client project?

**Comment by tlawrie** [comment]
Thanks @morarucostel . Closing issue.
